language: node_js

node_js:
  - 5.10

install:
  - npm install

  ## install the Cypress CLI Tools
  ## which gives us access to the
  ## `cypress` command used below
  - npm install -g cypress-cli

script:
  - npm run build

  - cypress ci