# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Cypress.io Documentation
subtitle: Testing, the way it should be.
description: Cypress is a test engine that runs unit and integration tests in your browser. It makes it easy to write and debug web application tests.
author: Cypress.io
language: en

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://docs.cypress.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

logo: img/logo.png
github: cypress-io/cypress

# Directory
source_dir: source
public_dir: public
i18n_dir: :lang
skip_render:

# Generate alias pages for redirecting to posts, pages or URL
# You must run `npm run build` for changes to take effect
# https://github.com/hexojs/hexo-generator-alias
# to redirect a directory, make sure it has a trailing slash (/docs/bob > /docs/bob/)
# can also do outside page links here
# plugins/index.html: https://github.com/cypress/cypress/wiki/Plugins
alias:
  index.html: guides/getting-started/why-cypress.html
  guides/index.html: guides/getting-started/why-cypress.html
  api/index.html: api/introduction/api.html
  examples/index.html: examples/recipes/unit-testing-recipe.html
  dashboard/index.html: dashboard/overview/features-dashboard.html
  faq/index.html: faq/questions/general-questions-faq.html
  docs/known-issues/: guides/references/known-issues.html
  docs/finding-elements/: guides/core-concepts/introduction-to-cypress.html#Querying-Elements

#from Google Search Console/Webmaster Tools since 7/3/2017 - https://docs.google.com/spreadsheets/d/1SHhjytMEzIxtdzFNXJHn_Q6p3xFFv_lFw0x_JtNtxt0/edit#gid=1581503717
  v1.0/docs/promise/: api/utilities/promise.html
  v1.0/docs/getcookie/: api/commands/getcookie.html
  v1.0/docs/getcookies/: api/commands/getcookies.html
  v1.0/docs/nextall/: api/commands/nextall.html
  v1.0/docs/prevuntil/: api/commands/prevuntil.html
  v1.0/docs/siblings/: api/commands/siblings.html
  guides/issuing-commands/: guides/core-concepts/introduction-to-cypress.html#Subject-Management
  v1.0/docs/clearcookie/: api/commands/clearcookie.html
  api/commands/api-server.html: api/cypress-api/cypress-server.html
  guides/installing-and-running/: guides/getting-started/installing-cypress.html
  docs/screenshots-and-videos/: guides/core-concepts/screenshots-and-videos.html
  docs/projects/: dashboard/overview/projects-dashboard.html
  docs/network-requests-xhr/: guides/guides/network-requests.html
  docs/environment-variables/: guides/guides/environment-variables.html
  api/commands/cypress-blob.html: api/utilities/blob.html
  docs/installing-and-running/: guides/getting-started/installing-cypress.html
  docs/configuration/: guides/references/configuration.html
  v1.0/docs/exec/: api/commands/exec.html
  v1.0/docs/setcookie/: api/commands/setcookie.html
  v1.0/docs/clear/: api/commands/clear.html
  v1.0/docs/cypress-minimatch/: api/utilities/minimatch.html
  v1.0/docs/first/: /api/commands/first.html
  docs/cli/: guides/guides/command-line.html
  docs/wait/: api/commands/wait.html
  why-cypress/: guides/getting-started/why-cypress.html
  guides.html/: guides/getting-started/why-cypress.html
  guides/references/type/: api/commands/type.html
  docs/launching-browsers/: guides/core-concepts/launching-browsers.html
  guides/integrating-cypress/features.html/: guides/guides/continuous-integration.html
  guides/network-requests-xhr/: guides/guides/network-requests.html

# Include/Exclude Files/Folders
include:
  - api/utilities/** ## This ensures that our '_.md' file is included

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false

# https://github.com/ele828/hexo-prism-plugin
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'coy'
  line_number: false    # default false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MM-DD-YYYY
time_format: HH:mm:ss

twitter_username: Cypress_io
facebook_username: cypressio
github_username: cypress-io
github_main_repo: cypress-io/cypress
email: support@cypress.io
gitter: cypress-io/cypress
facebook_admin_id: 22600147
facebook_app_id: 446223215719535

# Disqus settings
# _your_disqus_short_name_
disqus_shortname: cypress-documentation

# Google Plugins
google:
  analytics_id: UA-59606812-3
  optimize_id: GTM-MVNP9PH
  tag_manager_id: GTM-KNKBWLD

# Crash reporting
raygun:
  apiKey: SG5ZJfQICgeechPbpRE1DQ==

## Algolia Search
## https://github.com/LouisBarranqueiro/hexo-algoliasearch
algolia:
  en:
    # Algolia application ID
    app_id: "R9KDA5FMJB"
    # Algolia SEARCH ID (not Write or Admin)
    api_key: "8e6c3119ee78db1ad10cd7bfb439d726"
    index_name: "cypress"

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cypress

## https://github.com/mamboer/hexo-renderer-scss
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

## https://github.com/ludoviclefevre/hexo-generator-seo-friendly-sitemap
sitemap:
  path: sitemap.xml

## https://github.com/hexojs/hexo-renderer-marked
marked:
  autolink: false

## https://github.com/mamboer/hexo-filter-cleanup
hfc_useref:
  enable: true
  concat: true
  exclude:
hfc_html:
  enable: false
  exclude:
hfc_css:
  enable: true
  exclude:
    - '*.min.css'
hfc_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'
hfc_img:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  webp: true
  webpQuality: 75
  gifslice: true
  jpegtran: true
  jpegrecompress: false
  jpegrecompressQuality: 'medium'
  optipng: true
  svgo: false
hfc_favicons:
  enable: false
